import { useEffect, useState } from 'react'
import { api, send, type User, type Item, type Look, type Use, type Plan, type Preferences, type Capsule, type Inspiration, type Post, type Trip, type Feedback } from './lib'
import { Home, Closet, Looks, History, Favorites, Inspirations, Trips, Buy, Capsules, Profile, Stats } from './pages'

export type Page='home'|'closet'|'looks'|'history'|'favorites'|'inspirations'|'trips'|'buy'|'capsules'|'profile'|'stats'
export type Store={user:User;items:Item[];looks:Look[];uses:Use[];plans:Plan[];preferences:Preferences;capsules:Capsule[];inspirations:Inspiration[];posts:Post[];trips:Trip[];feedback:Feedback[];vision:boolean;reload:()=>Promise<void>;notice:(message:string)=>void;go:(page:Page)=>void}
const nav:{id:Page;label:string;icon:string}[]=[['home','Início','⌂'],['closet','Guarda-roupa','◇'],['looks','Looks','✧'],['history','Histórico','▦'],['favorites','Favoritos','♡'],['inspirations','Inspirações','☆'],['trips','Viagens','✈'],['buy','Analisar compra','◈'],['capsules','Cápsulas','▣'],['profile','Perfil','◌'],['stats','Estatísticas','▤']].map(([id,label,icon])=>({id:id as Page,label,icon}))

export default function App(){
  const [user,setUser]=useState<User|null>(null),[page,setPage]=useState<Page>('home'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[menu,setMenu]=useState(false),[vision,setVision]=useState(false)
  const [items,setItems]=useState<Item[]>([]),[looks,setLooks]=useState<Look[]>([]),[uses,setUses]=useState<Use[]>([]),[plans,setPlans]=useState<Plan[]>([]),[preferences,setPreferences]=useState<Preferences>({styles:'',colors:'',avoid_colors:'',item_types:'',notes:''}),[capsules,setCapsules]=useState<Capsule[]>([]),[inspirations,setInspirations]=useState<Inspiration[]>([]),[posts,setPosts]=useState<Post[]>([]),[trips,setTrips]=useState<Trip[]>([]),[feedback,setFeedback]=useState<Feedback[]>([])
  const [mode,setMode]=useState<'login'|'register'>('login'),[auth,setAuth]=useState({name:'',email:'',password:''})
  async function reload(){const data=await Promise.all([api<Item[]>('/items'),api<Look[]>('/looks'),api<Use[]>('/uses'),api<Plan[]>('/plans'),api<Preferences>('/preferences'),api<Capsule[]>('/capsules'),api<Inspiration[]>('/inspirations'),api<Post[]>('/posts'),api<Trip[]>('/trips'),api<Feedback[]>('/feedback'),api<User>('/me')]);setItems(data[0]);setLooks(data[1]);setUses(data[2]);setPlans(data[3]);setPreferences(data[4]);setCapsules(data[5]);setInspirations(data[6]);setPosts(data[7]);setTrips(data[8]);setFeedback(data[9]);setUser(data[10])}
  useEffect(()=>{(async()=>{try{setVision((await api<{vision:boolean}>('/features')).vision);if(localStorage.getItem('grwm-token')){setUser(await api<User>('/me'));await reload()}}catch{localStorage.removeItem('grwm-token')}finally{setLoading(false)}})()},[])
  async function authenticate(e:React.FormEvent){e.preventDefault();setError('');try{const data=await send<{token:string;user:User}>(mode==='login'?'/login':'/register','POST',auth);localStorage.setItem('grwm-token',data.token);setUser(data.user);await reload()}catch(e){setError((e as Error).message)}}
  async function logout(){try{await send('/logout','POST')}catch{}localStorage.removeItem('grwm-token');setUser(null);setPage('home')}
  const notice=(m:string)=>{setMessage(m);setTimeout(()=>setMessage(''),5000)}
  const go=(p:Page)=>{setPage(p);setMenu(false)}
  if(loading)return <div className="splash">Carregando GRWM…</div>
  if(!user)return <main className="auth-shell"><section className="auth-hero"><span>SEU CLOSET</span><h1>GRWM</h1><p>Seu guarda-roupa, com mais possibilidades.</p></section><section className="auth-panel"><form className="auth-card" onSubmit={authenticate}><span>SEU ESPAÇO</span><h2>{mode==='login'?'Entre na sua conta':'Crie sua conta'}</h2><p>Organize suas peças e descubra novas combinações.</p>{mode==='register'&&<label>Nome<input required minLength={2} value={auth.name} onChange={e=>setAuth({...auth,name:e.target.value})}/></label>}<label>E-mail<input required type="email" value={auth.email} onChange={e=>setAuth({...auth,email:e.target.value})}/></label><label>Senha<input required type="password" minLength={mode==='register'?8:1} value={auth.password} onChange={e=>setAuth({...auth,password:e.target.value})}/></label>{error&&<p role="alert" className="alert">{error}</p>}<button className="primary">{mode==='login'?'Entrar':'Criar conta'}</button><button type="button" className="link" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Criar conta':'Já tenho conta'}</button></form></section></main>
  const store:Store={user,items,looks,uses,plans,preferences,capsules,inspirations,posts,trips,feedback,vision,reload,notice,go}
  const pages={home:Home,closet:Closet,looks:Looks,history:History,favorites:Favorites,inspirations:Inspirations,trips:Trips,buy:Buy,capsules:Capsules,profile:Profile,stats:Stats}
  const Current=pages[page]
  return <div className="app-shell"><aside className={`sidebar ${menu?'open':''}`}><div className="brand"><small>SEU CLOSET</small><strong>GRWM</strong></div><nav aria-label="Navegação principal">{nav.map(n=><button key={n.id} className={page===n.id?'active':''} onClick={()=>go(n.id)}><span>{n.icon}</span>{n.label}</button>)}</nav><div className="sidebar-foot"><strong>{user.name}</strong><button onClick={logout}>Sair da conta</button></div></aside><div className="main-shell"><header className="topbar"><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Abrir menu">☰</button><strong>GRWM</strong><button onClick={()=>go('profile')}>{user.name.split(' ')[0]} ◌</button></header><main className="content">{message&&<div className="toast" role="status">{message}</div>}<Current {...store}/></main></div></div>
}

